[project]
name = "02_python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "whatuknow", email = "csong1501@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.31.0",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
]
